/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAlimentosRouteImport } from './routes/_authenticated/alimentos'
import { Route as AuthenticatedAlimentacaoRouteImport } from './routes/_authenticated/alimentacao'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlimentosRoute = AuthenticatedAlimentosRouteImport.update({
  id: '/alimentos',
  path: '/alimentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlimentacaoRoute =
  AuthenticatedAlimentacaoRouteImport.update({
    id: '/alimentacao',
    path: '/alimentacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alimentacao': typeof AuthenticatedAlimentacaoRoute
  '/alimentos': typeof AuthenticatedAlimentosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/perfil': typeof AuthenticatedPerfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alimentacao': typeof AuthenticatedAlimentacaoRoute
  '/alimentos': typeof AuthenticatedAlimentosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/perfil': typeof AuthenticatedPerfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alimentacao': typeof AuthenticatedAlimentacaoRoute
  '/_authenticated/alimentos': typeof AuthenticatedAlimentosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alimentacao'
    | '/alimentos'
    | '/dashboard'
    | '/perfil'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/alimentacao' | '/alimentos' | '/dashboard' | '/perfil'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/alimentacao'
    | '/_authenticated/alimentos'
    | '/_authenticated/dashboard'
    | '/_authenticated/perfil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alimentos': {
      id: '/_authenticated/alimentos'
      path: '/alimentos'
      fullPath: '/alimentos'
      preLoaderRoute: typeof AuthenticatedAlimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alimentacao': {
      id: '/_authenticated/alimentacao'
      path: '/alimentacao'
      fullPath: '/alimentacao'
      preLoaderRoute: typeof AuthenticatedAlimentacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlimentacaoRoute: typeof AuthenticatedAlimentacaoRoute
  AuthenticatedAlimentosRoute: typeof AuthenticatedAlimentosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlimentacaoRoute: AuthenticatedAlimentacaoRoute,
  AuthenticatedAlimentosRoute: AuthenticatedAlimentosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
