/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTreinosRouteImport } from './routes/_authenticated/treinos'
import { Route as AuthenticatedTreinoHojeRouteImport } from './routes/_authenticated/treino-hoje'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPlanejamentoSemanalRouteImport } from './routes/_authenticated/planejamento-semanal'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedModelosTreinoRouteImport } from './routes/_authenticated/modelos-treino'
import { Route as AuthenticatedHistoricoTreinosRouteImport } from './routes/_authenticated/historico-treinos'
import { Route as AuthenticatedHidratacaoRouteImport } from './routes/_authenticated/hidratacao'
import { Route as AuthenticatedEvolucaoFisicaRouteImport } from './routes/_authenticated/evolucao-fisica'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAlimentosRouteImport } from './routes/_authenticated/alimentos'
import { Route as AuthenticatedAlimentacaoRouteImport } from './routes/_authenticated/alimentacao'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin/logs'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTreinosRoute = AuthenticatedTreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTreinoHojeRoute = AuthenticatedTreinoHojeRouteImport.update({
  id: '/treino-hoje',
  path: '/treino-hoje',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanejamentoSemanalRoute =
  AuthenticatedPlanejamentoSemanalRouteImport.update({
    id: '/planejamento-semanal',
    path: '/planejamento-semanal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModelosTreinoRoute =
  AuthenticatedModelosTreinoRouteImport.update({
    id: '/modelos-treino',
    path: '/modelos-treino',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoTreinosRoute =
  AuthenticatedHistoricoTreinosRouteImport.update({
    id: '/historico-treinos',
    path: '/historico-treinos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHidratacaoRoute = AuthenticatedHidratacaoRouteImport.update({
  id: '/hidratacao',
  path: '/hidratacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvolucaoFisicaRoute =
  AuthenticatedEvolucaoFisicaRouteImport.update({
    id: '/evolucao-fisica',
    path: '/evolucao-fisica',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlimentosRoute = AuthenticatedAlimentosRouteImport.update({
  id: '/alimentos',
  path: '/alimentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlimentacaoRoute =
  AuthenticatedAlimentacaoRouteImport.update({
    id: '/alimentacao',
    path: '/alimentacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/alimentacao': typeof AuthenticatedAlimentacaoRoute
  '/alimentos': typeof AuthenticatedAlimentosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/evolucao-fisica': typeof AuthenticatedEvolucaoFisicaRoute
  '/hidratacao': typeof AuthenticatedHidratacaoRoute
  '/historico-treinos': typeof AuthenticatedHistoricoTreinosRoute
  '/modelos-treino': typeof AuthenticatedModelosTreinoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/planejamento-semanal': typeof AuthenticatedPlanejamentoSemanalRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/treino-hoje': typeof AuthenticatedTreinoHojeRoute
  '/treinos': typeof AuthenticatedTreinosRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alimentacao': typeof AuthenticatedAlimentacaoRoute
  '/alimentos': typeof AuthenticatedAlimentosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/evolucao-fisica': typeof AuthenticatedEvolucaoFisicaRoute
  '/hidratacao': typeof AuthenticatedHidratacaoRoute
  '/historico-treinos': typeof AuthenticatedHistoricoTreinosRoute
  '/modelos-treino': typeof AuthenticatedModelosTreinoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/planejamento-semanal': typeof AuthenticatedPlanejamentoSemanalRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/treino-hoje': typeof AuthenticatedTreinoHojeRoute
  '/treinos': typeof AuthenticatedTreinosRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/alimentacao': typeof AuthenticatedAlimentacaoRoute
  '/_authenticated/alimentos': typeof AuthenticatedAlimentosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/evolucao-fisica': typeof AuthenticatedEvolucaoFisicaRoute
  '/_authenticated/hidratacao': typeof AuthenticatedHidratacaoRoute
  '/_authenticated/historico-treinos': typeof AuthenticatedHistoricoTreinosRoute
  '/_authenticated/modelos-treino': typeof AuthenticatedModelosTreinoRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/planejamento-semanal': typeof AuthenticatedPlanejamentoSemanalRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/treino-hoje': typeof AuthenticatedTreinoHojeRoute
  '/_authenticated/treinos': typeof AuthenticatedTreinosRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/alimentacao'
    | '/alimentos'
    | '/dashboard'
    | '/evolucao-fisica'
    | '/hidratacao'
    | '/historico-treinos'
    | '/modelos-treino'
    | '/perfil'
    | '/planejamento-semanal'
    | '/relatorios'
    | '/treino-hoje'
    | '/treinos'
    | '/admin/logs'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/alimentacao'
    | '/alimentos'
    | '/dashboard'
    | '/evolucao-fisica'
    | '/hidratacao'
    | '/historico-treinos'
    | '/modelos-treino'
    | '/perfil'
    | '/planejamento-semanal'
    | '/relatorios'
    | '/treino-hoje'
    | '/treinos'
    | '/admin/logs'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/alimentacao'
    | '/_authenticated/alimentos'
    | '/_authenticated/dashboard'
    | '/_authenticated/evolucao-fisica'
    | '/_authenticated/hidratacao'
    | '/_authenticated/historico-treinos'
    | '/_authenticated/modelos-treino'
    | '/_authenticated/perfil'
    | '/_authenticated/planejamento-semanal'
    | '/_authenticated/relatorios'
    | '/_authenticated/treino-hoje'
    | '/_authenticated/treinos'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/treinos': {
      id: '/_authenticated/treinos'
      path: '/treinos'
      fullPath: '/treinos'
      preLoaderRoute: typeof AuthenticatedTreinosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treino-hoje': {
      id: '/_authenticated/treino-hoje'
      path: '/treino-hoje'
      fullPath: '/treino-hoje'
      preLoaderRoute: typeof AuthenticatedTreinoHojeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planejamento-semanal': {
      id: '/_authenticated/planejamento-semanal'
      path: '/planejamento-semanal'
      fullPath: '/planejamento-semanal'
      preLoaderRoute: typeof AuthenticatedPlanejamentoSemanalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modelos-treino': {
      id: '/_authenticated/modelos-treino'
      path: '/modelos-treino'
      fullPath: '/modelos-treino'
      preLoaderRoute: typeof AuthenticatedModelosTreinoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico-treinos': {
      id: '/_authenticated/historico-treinos'
      path: '/historico-treinos'
      fullPath: '/historico-treinos'
      preLoaderRoute: typeof AuthenticatedHistoricoTreinosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hidratacao': {
      id: '/_authenticated/hidratacao'
      path: '/hidratacao'
      fullPath: '/hidratacao'
      preLoaderRoute: typeof AuthenticatedHidratacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evolucao-fisica': {
      id: '/_authenticated/evolucao-fisica'
      path: '/evolucao-fisica'
      fullPath: '/evolucao-fisica'
      preLoaderRoute: typeof AuthenticatedEvolucaoFisicaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alimentos': {
      id: '/_authenticated/alimentos'
      path: '/alimentos'
      fullPath: '/alimentos'
      preLoaderRoute: typeof AuthenticatedAlimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alimentacao': {
      id: '/_authenticated/alimentacao'
      path: '/alimentacao'
      fullPath: '/alimentacao'
      preLoaderRoute: typeof AuthenticatedAlimentacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAlimentacaoRoute: typeof AuthenticatedAlimentacaoRoute
  AuthenticatedAlimentosRoute: typeof AuthenticatedAlimentosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEvolucaoFisicaRoute: typeof AuthenticatedEvolucaoFisicaRoute
  AuthenticatedHidratacaoRoute: typeof AuthenticatedHidratacaoRoute
  AuthenticatedHistoricoTreinosRoute: typeof AuthenticatedHistoricoTreinosRoute
  AuthenticatedModelosTreinoRoute: typeof AuthenticatedModelosTreinoRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPlanejamentoSemanalRoute: typeof AuthenticatedPlanejamentoSemanalRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedTreinoHojeRoute: typeof AuthenticatedTreinoHojeRoute
  AuthenticatedTreinosRoute: typeof AuthenticatedTreinosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAlimentacaoRoute: AuthenticatedAlimentacaoRoute,
  AuthenticatedAlimentosRoute: AuthenticatedAlimentosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEvolucaoFisicaRoute: AuthenticatedEvolucaoFisicaRoute,
  AuthenticatedHidratacaoRoute: AuthenticatedHidratacaoRoute,
  AuthenticatedHistoricoTreinosRoute: AuthenticatedHistoricoTreinosRoute,
  AuthenticatedModelosTreinoRoute: AuthenticatedModelosTreinoRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPlanejamentoSemanalRoute: AuthenticatedPlanejamentoSemanalRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedTreinoHojeRoute: AuthenticatedTreinoHojeRoute,
  AuthenticatedTreinosRoute: AuthenticatedTreinosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
