/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTreinosRouteImport } from './routes/_authenticated/treinos'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMeuTreinoRouteImport } from './routes/_authenticated/meu-treino'
import { Route as AuthenticatedHistoricoTreinosRouteImport } from './routes/_authenticated/historico-treinos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAlimentosRouteImport } from './routes/_authenticated/alimentos'
import { Route as AuthenticatedAlimentacaoRouteImport } from './routes/_authenticated/alimentacao'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTreinosRoute = AuthenticatedTreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeuTreinoRoute = AuthenticatedMeuTreinoRouteImport.update({
  id: '/meu-treino',
  path: '/meu-treino',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoTreinosRoute =
  AuthenticatedHistoricoTreinosRouteImport.update({
    id: '/historico-treinos',
    path: '/historico-treinos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlimentosRoute = AuthenticatedAlimentosRouteImport.update({
  id: '/alimentos',
  path: '/alimentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlimentacaoRoute =
  AuthenticatedAlimentacaoRouteImport.update({
    id: '/alimentacao',
    path: '/alimentacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alimentacao': typeof AuthenticatedAlimentacaoRoute
  '/alimentos': typeof AuthenticatedAlimentosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historico-treinos': typeof AuthenticatedHistoricoTreinosRoute
  '/meu-treino': typeof AuthenticatedMeuTreinoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/treinos': typeof AuthenticatedTreinosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alimentacao': typeof AuthenticatedAlimentacaoRoute
  '/alimentos': typeof AuthenticatedAlimentosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historico-treinos': typeof AuthenticatedHistoricoTreinosRoute
  '/meu-treino': typeof AuthenticatedMeuTreinoRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/treinos': typeof AuthenticatedTreinosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alimentacao': typeof AuthenticatedAlimentacaoRoute
  '/_authenticated/alimentos': typeof AuthenticatedAlimentosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/historico-treinos': typeof AuthenticatedHistoricoTreinosRoute
  '/_authenticated/meu-treino': typeof AuthenticatedMeuTreinoRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/treinos': typeof AuthenticatedTreinosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alimentacao'
    | '/alimentos'
    | '/dashboard'
    | '/historico-treinos'
    | '/meu-treino'
    | '/perfil'
    | '/relatorios'
    | '/treinos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/alimentacao'
    | '/alimentos'
    | '/dashboard'
    | '/historico-treinos'
    | '/meu-treino'
    | '/perfil'
    | '/relatorios'
    | '/treinos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/alimentacao'
    | '/_authenticated/alimentos'
    | '/_authenticated/dashboard'
    | '/_authenticated/historico-treinos'
    | '/_authenticated/meu-treino'
    | '/_authenticated/perfil'
    | '/_authenticated/relatorios'
    | '/_authenticated/treinos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/treinos': {
      id: '/_authenticated/treinos'
      path: '/treinos'
      fullPath: '/treinos'
      preLoaderRoute: typeof AuthenticatedTreinosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-treino': {
      id: '/_authenticated/meu-treino'
      path: '/meu-treino'
      fullPath: '/meu-treino'
      preLoaderRoute: typeof AuthenticatedMeuTreinoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico-treinos': {
      id: '/_authenticated/historico-treinos'
      path: '/historico-treinos'
      fullPath: '/historico-treinos'
      preLoaderRoute: typeof AuthenticatedHistoricoTreinosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alimentos': {
      id: '/_authenticated/alimentos'
      path: '/alimentos'
      fullPath: '/alimentos'
      preLoaderRoute: typeof AuthenticatedAlimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alimentacao': {
      id: '/_authenticated/alimentacao'
      path: '/alimentacao'
      fullPath: '/alimentacao'
      preLoaderRoute: typeof AuthenticatedAlimentacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlimentacaoRoute: typeof AuthenticatedAlimentacaoRoute
  AuthenticatedAlimentosRoute: typeof AuthenticatedAlimentosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoricoTreinosRoute: typeof AuthenticatedHistoricoTreinosRoute
  AuthenticatedMeuTreinoRoute: typeof AuthenticatedMeuTreinoRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedTreinosRoute: typeof AuthenticatedTreinosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlimentacaoRoute: AuthenticatedAlimentacaoRoute,
  AuthenticatedAlimentosRoute: AuthenticatedAlimentosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoricoTreinosRoute: AuthenticatedHistoricoTreinosRoute,
  AuthenticatedMeuTreinoRoute: AuthenticatedMeuTreinoRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedTreinosRoute: AuthenticatedTreinosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
